/**
 * Copyright (c) 2018 SyndLoanHub, LLC and contributors
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License from within this distribution and at:
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 */

package com.syndloanhub.loansum.product.facility.prorated;

import org.joda.beans.ImmutableBean;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.gen.PropertyDefinition;

import static com.syndloanhub.loansum.product.facility.LoanContractEventType.RepaymentEvent;

import java.time.LocalDate;
import java.util.Map;
import java.util.NoSuchElementException;
import org.joda.beans.MetaBean;
import org.joda.beans.MetaProperty;
import org.joda.beans.impl.direct.DirectFieldsBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import com.opengamma.strata.basics.currency.CurrencyAmount;
import com.syndloanhub.loansum.product.facility.LoanContractEventType;

import org.joda.beans.Bean;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.impl.direct.DirectMetaProperty;

/**
 * Repayment represents a contract-level event repaying funded principal.
 */
@BeanDefinition
public class ProratedRepayment implements ProratedLoanContractEvent, ImmutableBean {

  /**
   * Return type RepaymentEvent.
   */
  @Override
  public LoanContractEventType getType() {
    return RepaymentEvent;
  }

  /**
   * The effective date of the event.
   */
  @PropertyDefinition(validate = "notNull")
  private final LocalDate effectiveDate;

  /**
   * The contract event global amount.
   * <p>
   * The event global amount represents the amount of the event, and must be non-negative.
   */
  @PropertyDefinition(validate = "notNull")
  private final CurrencyAmount amount;

  /**
   * Interest-on-paydown flag.
   * <p>
   * If true, interest on repaid principal is paid on the repayment
   * date, not the contract end date.
   */
  @PropertyDefinition(validate = "")
  private final boolean interestOnPaydown;

  /**
   * The price of the repaid principal, default par.
   */
  @PropertyDefinition(validate = "")
  private final double price;

  //------------------------- AUTOGENERATED START -------------------------
  /**
   * The meta-bean for {@code ProratedRepayment}.
   * @return the meta-bean, not null
   */
  public static ProratedRepayment.Meta meta() {
    return ProratedRepayment.Meta.INSTANCE;
  }

  static {
    MetaBean.register(ProratedRepayment.Meta.INSTANCE);
  }

  /**
   * Returns a builder used to create an instance of the bean.
   * @return the builder, not null
   */
  public static ProratedRepayment.Builder builder() {
    return new ProratedRepayment.Builder();
  }

  /**
   * Restricted constructor.
   * @param builder  the builder to copy from, not null
   */
  protected ProratedRepayment(ProratedRepayment.Builder builder) {
    JodaBeanUtils.notNull(builder.effectiveDate, "effectiveDate");
    JodaBeanUtils.notNull(builder.amount, "amount");
    this.effectiveDate = builder.effectiveDate;
    this.amount = builder.amount;
    this.interestOnPaydown = builder.interestOnPaydown;
    this.price = builder.price;
  }

  @Override
  public ProratedRepayment.Meta metaBean() {
    return ProratedRepayment.Meta.INSTANCE;
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the effective date of the event.
   * @return the value of the property, not null
   */
  public LocalDate getEffectiveDate() {
    return effectiveDate;
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the contract event global amount.
   * <p>
   * The event global amount represents the amount of the event, and must be non-negative.
   * @return the value of the property, not null
   */
  public CurrencyAmount getAmount() {
    return amount;
  }

  //-----------------------------------------------------------------------
  /**
   * Gets interest-on-paydown flag.
   * <p>
   * If true, interest on repaid principal is paid on the repayment
   * date, not the contract end date.
   * @return the value of the property
   */
  public boolean isInterestOnPaydown() {
    return interestOnPaydown;
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the price of the repaid principal, default par.
   * @return the value of the property
   */
  public double getPrice() {
    return price;
  }

  //-----------------------------------------------------------------------
  /**
   * Returns a builder that allows this bean to be mutated.
   * @return the mutable builder, not null
   */
  public Builder toBuilder() {
    return new Builder(this);
  }

  @Override
  public boolean equals(Object obj) {
    if (obj == this) {
      return true;
    }
    if (obj != null && obj.getClass() == this.getClass()) {
      ProratedRepayment other = (ProratedRepayment) obj;
      return JodaBeanUtils.equal(effectiveDate, other.effectiveDate) &&
          JodaBeanUtils.equal(amount, other.amount) &&
          (interestOnPaydown == other.interestOnPaydown) &&
          JodaBeanUtils.equal(price, other.price);
    }
    return false;
  }

  @Override
  public int hashCode() {
    int hash = getClass().hashCode();
    hash = hash * 31 + JodaBeanUtils.hashCode(effectiveDate);
    hash = hash * 31 + JodaBeanUtils.hashCode(amount);
    hash = hash * 31 + JodaBeanUtils.hashCode(interestOnPaydown);
    hash = hash * 31 + JodaBeanUtils.hashCode(price);
    return hash;
  }

  @Override
  public String toString() {
    StringBuilder buf = new StringBuilder(160);
    buf.append("ProratedRepayment{");
    int len = buf.length();
    toString(buf);
    if (buf.length() > len) {
      buf.setLength(buf.length() - 2);
    }
    buf.append('}');
    return buf.toString();
  }

  protected void toString(StringBuilder buf) {
    buf.append("effectiveDate").append('=').append(JodaBeanUtils.toString(effectiveDate)).append(',').append(' ');
    buf.append("amount").append('=').append(JodaBeanUtils.toString(amount)).append(',').append(' ');
    buf.append("interestOnPaydown").append('=').append(JodaBeanUtils.toString(interestOnPaydown)).append(',').append(' ');
    buf.append("price").append('=').append(JodaBeanUtils.toString(price)).append(',').append(' ');
  }

  //-----------------------------------------------------------------------
  /**
   * The meta-bean for {@code ProratedRepayment}.
   */
  public static class Meta extends DirectMetaBean {
    /**
     * The singleton instance of the meta-bean.
     */
    static final Meta INSTANCE = new Meta();

    /**
     * The meta-property for the {@code effectiveDate} property.
     */
    private final MetaProperty<LocalDate> _effectiveDate = DirectMetaProperty.ofImmutable(
        this, "effectiveDate", ProratedRepayment.class, LocalDate.class);
    /**
     * The meta-property for the {@code amount} property.
     */
    private final MetaProperty<CurrencyAmount> _amount = DirectMetaProperty.ofImmutable(
        this, "amount", ProratedRepayment.class, CurrencyAmount.class);
    /**
     * The meta-property for the {@code interestOnPaydown} property.
     */
    private final MetaProperty<Boolean> _interestOnPaydown = DirectMetaProperty.ofImmutable(
        this, "interestOnPaydown", ProratedRepayment.class, Boolean.TYPE);
    /**
     * The meta-property for the {@code price} property.
     */
    private final MetaProperty<Double> _price = DirectMetaProperty.ofImmutable(
        this, "price", ProratedRepayment.class, Double.TYPE);
    /**
     * The meta-properties.
     */
    private final Map<String, MetaProperty<?>> _metaPropertyMap$ = new DirectMetaPropertyMap(
        this, null,
        "effectiveDate",
        "amount",
        "interestOnPaydown",
        "price");

    /**
     * Restricted constructor.
     */
    protected Meta() {
    }

    @Override
    protected MetaProperty<?> metaPropertyGet(String propertyName) {
      switch (propertyName.hashCode()) {
        case -930389515:  // effectiveDate
          return _effectiveDate;
        case -1413853096:  // amount
          return _amount;
        case 1105799777:  // interestOnPaydown
          return _interestOnPaydown;
        case 106934601:  // price
          return _price;
      }
      return super.metaPropertyGet(propertyName);
    }

    @Override
    public ProratedRepayment.Builder builder() {
      return new ProratedRepayment.Builder();
    }

    @Override
    public Class<? extends ProratedRepayment> beanType() {
      return ProratedRepayment.class;
    }

    @Override
    public Map<String, MetaProperty<?>> metaPropertyMap() {
      return _metaPropertyMap$;
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-property for the {@code effectiveDate} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<LocalDate> effectiveDate() {
      return _effectiveDate;
    }

    /**
     * The meta-property for the {@code amount} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<CurrencyAmount> amount() {
      return _amount;
    }

    /**
     * The meta-property for the {@code interestOnPaydown} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<Boolean> interestOnPaydown() {
      return _interestOnPaydown;
    }

    /**
     * The meta-property for the {@code price} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<Double> price() {
      return _price;
    }

    //-----------------------------------------------------------------------
    @Override
    protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
      switch (propertyName.hashCode()) {
        case -930389515:  // effectiveDate
          return ((ProratedRepayment) bean).getEffectiveDate();
        case -1413853096:  // amount
          return ((ProratedRepayment) bean).getAmount();
        case 1105799777:  // interestOnPaydown
          return ((ProratedRepayment) bean).isInterestOnPaydown();
        case 106934601:  // price
          return ((ProratedRepayment) bean).getPrice();
      }
      return super.propertyGet(bean, propertyName, quiet);
    }

    @Override
    protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
      metaProperty(propertyName);
      if (quiet) {
        return;
      }
      throw new UnsupportedOperationException("Property cannot be written: " + propertyName);
    }

  }

  //-----------------------------------------------------------------------
  /**
   * The bean-builder for {@code ProratedRepayment}.
   */
  public static class Builder extends DirectFieldsBeanBuilder<ProratedRepayment> {

    private LocalDate effectiveDate;
    private CurrencyAmount amount;
    private boolean interestOnPaydown;
    private double price;

    /**
     * Restricted constructor.
     */
    protected Builder() {
    }

    /**
     * Restricted copy constructor.
     * @param beanToCopy  the bean to copy from, not null
     */
    protected Builder(ProratedRepayment beanToCopy) {
      this.effectiveDate = beanToCopy.getEffectiveDate();
      this.amount = beanToCopy.getAmount();
      this.interestOnPaydown = beanToCopy.isInterestOnPaydown();
      this.price = beanToCopy.getPrice();
    }

    //-----------------------------------------------------------------------
    @Override
    public Object get(String propertyName) {
      switch (propertyName.hashCode()) {
        case -930389515:  // effectiveDate
          return effectiveDate;
        case -1413853096:  // amount
          return amount;
        case 1105799777:  // interestOnPaydown
          return interestOnPaydown;
        case 106934601:  // price
          return price;
        default:
          throw new NoSuchElementException("Unknown property: " + propertyName);
      }
    }

    @Override
    public Builder set(String propertyName, Object newValue) {
      switch (propertyName.hashCode()) {
        case -930389515:  // effectiveDate
          this.effectiveDate = (LocalDate) newValue;
          break;
        case -1413853096:  // amount
          this.amount = (CurrencyAmount) newValue;
          break;
        case 1105799777:  // interestOnPaydown
          this.interestOnPaydown = (Boolean) newValue;
          break;
        case 106934601:  // price
          this.price = (Double) newValue;
          break;
        default:
          throw new NoSuchElementException("Unknown property: " + propertyName);
      }
      return this;
    }

    @Override
    public Builder set(MetaProperty<?> property, Object value) {
      super.set(property, value);
      return this;
    }

    @Override
    public ProratedRepayment build() {
      return new ProratedRepayment(this);
    }

    //-----------------------------------------------------------------------
    /**
     * Sets the effective date of the event.
     * @param effectiveDate  the new value, not null
     * @return this, for chaining, not null
     */
    public Builder effectiveDate(LocalDate effectiveDate) {
      JodaBeanUtils.notNull(effectiveDate, "effectiveDate");
      this.effectiveDate = effectiveDate;
      return this;
    }

    /**
     * Sets the contract event global amount.
     * <p>
     * The event global amount represents the amount of the event, and must be non-negative.
     * @param amount  the new value, not null
     * @return this, for chaining, not null
     */
    public Builder amount(CurrencyAmount amount) {
      JodaBeanUtils.notNull(amount, "amount");
      this.amount = amount;
      return this;
    }

    /**
     * Sets interest-on-paydown flag.
     * <p>
     * If true, interest on repaid principal is paid on the repayment
     * date, not the contract end date.
     * @param interestOnPaydown  the new value
     * @return this, for chaining, not null
     */
    public Builder interestOnPaydown(boolean interestOnPaydown) {
      this.interestOnPaydown = interestOnPaydown;
      return this;
    }

    /**
     * Sets the price of the repaid principal, default par.
     * @param price  the new value
     * @return this, for chaining, not null
     */
    public Builder price(double price) {
      this.price = price;
      return this;
    }

    //-----------------------------------------------------------------------
    @Override
    public String toString() {
      StringBuilder buf = new StringBuilder(160);
      buf.append("ProratedRepayment.Builder{");
      int len = buf.length();
      toString(buf);
      if (buf.length() > len) {
        buf.setLength(buf.length() - 2);
      }
      buf.append('}');
      return buf.toString();
    }

    protected void toString(StringBuilder buf) {
      buf.append("effectiveDate").append('=').append(JodaBeanUtils.toString(effectiveDate)).append(',').append(' ');
      buf.append("amount").append('=').append(JodaBeanUtils.toString(amount)).append(',').append(' ');
      buf.append("interestOnPaydown").append('=').append(JodaBeanUtils.toString(interestOnPaydown)).append(',').append(' ');
      buf.append("price").append('=').append(JodaBeanUtils.toString(price)).append(',').append(' ');
    }

  }

  //-------------------------- AUTOGENERATED END --------------------------
}
